[package]
name = "alvio-egress"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
alvio-core = { path = "../alvio-core" }
alvio-webrtc = { path = "../alvio-webrtc" }
alvio-sfu = { path = "../alvio-sfu" }
alvio-storage = { path = "../alvio-storage" }
tokio = { workspace = true }
bytes = { workspace = true }
dashmap = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
